---
- name: upgrade transmission packages
  community.general.opkg:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - transmission-cfp-daemon
    - transmission-web
  notify: restar transmission